#!/usr/bin/env node

'use strict';

const pkgJSON = require(`${process.cwd()}/package.json`);
const shouldRun = Boolean(pkgJSON['_where']);

if (!shouldRun) return;

getGulpBin((bin) => {
	const fork = require('child_process').fork;
	fork(bin, ['release']);
});

function getGulpBin(callback) {
	const exec = require('child_process').exec;
	exec('npm bin', (err, stdout, stderr) => {
		callback(err, `${stdout}/gulp`)
	});
}
