#!/usr/bin/env node

'use strict';

const cwd = process.cwd();
const pkgJSON = require(`${cwd}/package.json`);
const shouldRun = Boolean(pkgJSON['_where']);

if (!shouldRun) return;

getGulpBin((error, bin) => {
	if (error) return console.error(error);

	console.log('fork cwd: ', cwd);

	const fork = require('child_process').fork;
	fork(bin, {cwd: cwd}, ['release']);
});

function getGulpBin(callback) {
	const exec = require('child_process').exec;
	console.log('exec cwd: ', pkgJSON['_where']);
	exec('npm bin', {cwd: pkgJSON['_where']}, (err, stdout, stderr) => {
		const bin = String(stdout).replace(/[\r\n\s]*$/, '');
		callback(err, `${bin}/gulp`)
	});
}
